<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315230238 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE destination (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, long_description TEXT DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, activity_tags JSON DEFAULT NULL, best_months JSON DEFAULT NULL, min_days INT DEFAULT NULL, max_days INT DEFAULT NULL, budget_level VARCHAR(50) DEFAULT NULL, difficulty_level VARCHAR(50) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3EC63EAA989D9B62 ON destination (slug)');
        $this->addSql('CREATE TABLE guide (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, guide_type VARCHAR(100) DEFAULT NULL, languages JSON DEFAULT NULL, regions_supported JSON DEFAULT NULL, daily_rate_from NUMERIC(12, 2) DEFAULT NULL, daily_rate_to NUMERIC(12, 2) DEFAULT NULL, specialties JSON DEFAULT NULL, certification_notes TEXT DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, contact_phone VARCHAR(50) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE hotel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(100) DEFAULT NULL, nightly_price_from NUMERIC(12, 2) DEFAULT NULL, nightly_price_to NUMERIC(12, 2) DEFAULT NULL, amenities JSON DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, contact_phone VARCHAR(50) DEFAULT NULL, notes TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, destination_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3535ED9816C6140 ON hotel (destination_id)');
        $this->addSql('CREATE TABLE itinerary_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, trip_type VARCHAR(100) DEFAULT NULL, duration_days INT DEFAULT NULL, budget_level VARCHAR(50) DEFAULT NULL, comfort_level VARCHAR(50) DEFAULT NULL, difficulty_level VARCHAR(50) DEFAULT NULL, interest_tags JSON DEFAULT NULL, summary TEXT DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B6822B42989D9B62 ON itinerary_template (slug)');
        $this->addSql('CREATE TABLE itinerary_template_day (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_number INT NOT NULL, title VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, hotel_category VARCHAR(100) DEFAULT NULL, transport_type VARCHAR(100) DEFAULT NULL, guide_type VARCHAR(100) DEFAULT NULL, activity_notes TEXT DEFAULT NULL, itinerary_template_id INT NOT NULL, destination_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8679E5AD6099834D ON itinerary_template_day (itinerary_template_id)');
        $this->addSql('CREATE INDEX IDX_8679E5AD816C6140 ON itinerary_template_day (destination_id)');
        $this->addSql('CREATE TABLE representative (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, whatsapp VARCHAR(50) DEFAULT NULL, languages JSON DEFAULT NULL, active_hours VARCHAR(255) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE transport_service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, service_type VARCHAR(100) DEFAULT NULL, vehicle_type VARCHAR(100) DEFAULT NULL, capacity INT DEFAULT NULL, base_area VARCHAR(255) DEFAULT NULL, price_notes TEXT DEFAULT NULL, contact_name VARCHAR(255) DEFAULT NULL, contact_phone VARCHAR(50) DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE hotel ADD CONSTRAINT FK_3535ED9816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE itinerary_template_day ADD CONSTRAINT FK_8679E5AD6099834D FOREIGN KEY (itinerary_template_id) REFERENCES itinerary_template (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE itinerary_template_day ADD CONSTRAINT FK_8679E5AD816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE hotel DROP CONSTRAINT FK_3535ED9816C6140');
        $this->addSql('ALTER TABLE itinerary_template_day DROP CONSTRAINT FK_8679E5AD6099834D');
        $this->addSql('ALTER TABLE itinerary_template_day DROP CONSTRAINT FK_8679E5AD816C6140');
        $this->addSql('DROP TABLE destination');
        $this->addSql('DROP TABLE guide');
        $this->addSql('DROP TABLE hotel');
        $this->addSql('DROP TABLE itinerary_template');
        $this->addSql('DROP TABLE itinerary_template_day');
        $this->addSql('DROP TABLE representative');
        $this->addSql('DROP TABLE transport_service');
    }
}
