<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260315231500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add Region and Supplier entities and link Hotel, Guide, TransportService to Supplier';
    }

    public function up(Schema $schema): void
    {
        // region table
        $this->addSql('CREATE TABLE region (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            country VARCHAR(255) NOT NULL,
            name VARCHAR(255) NOT NULL,
            slug VARCHAR(255) NOT NULL,
            is_active BOOLEAN DEFAULT true NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE UNIQUE INDEX uniq_region_slug ON region (slug)');

        // supplier table
        $this->addSql('CREATE TABLE supplier (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            supplier_type VARCHAR(100) DEFAULT NULL,
            contact_name VARCHAR(255) DEFAULT NULL,
            contact_email VARCHAR(255) DEFAULT NULL,
            contact_phone VARCHAR(50) DEFAULT NULL,
            notes TEXT DEFAULT NULL,
            is_active BOOLEAN DEFAULT true NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');

        // supplier_region join table
        $this->addSql('CREATE TABLE supplier_region (
            supplier_id INT NOT NULL,
            region_id INT NOT NULL,
            PRIMARY KEY(supplier_id, region_id)
        )');
        $this->addSql('CREATE INDEX idx_supplier_region_supplier ON supplier_region (supplier_id)');
        $this->addSql('CREATE INDEX idx_supplier_region_region ON supplier_region (region_id)');
        $this->addSql('ALTER TABLE supplier_region ADD CONSTRAINT fk_supplier_region_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE supplier_region ADD CONSTRAINT fk_supplier_region_region FOREIGN KEY (region_id) REFERENCES region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // add supplier_id to hotel
        $this->addSql('ALTER TABLE hotel ADD supplier_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_hotel_supplier ON hotel (supplier_id)');
        $this->addSql('ALTER TABLE hotel ADD CONSTRAINT fk_hotel_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // add supplier_id to guide
        $this->addSql('ALTER TABLE guide ADD supplier_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_guide_supplier ON guide (supplier_id)');
        $this->addSql('ALTER TABLE guide ADD CONSTRAINT fk_guide_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        // add supplier_id to transport_service
        $this->addSql('ALTER TABLE transport_service ADD supplier_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_transport_service_supplier ON transport_service (supplier_id)');
        $this->addSql('ALTER TABLE transport_service ADD CONSTRAINT fk_transport_service_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // drop FKs and columns from existing tables
        $this->addSql('ALTER TABLE hotel DROP CONSTRAINT fk_hotel_supplier');
        $this->addSql('ALTER TABLE guide DROP CONSTRAINT fk_guide_supplier');
        $this->addSql('ALTER TABLE transport_service DROP CONSTRAINT fk_transport_service_supplier');

        $this->addSql('DROP INDEX idx_hotel_supplier');
        $this->addSql('DROP INDEX idx_guide_supplier');
        $this->addSql('DROP INDEX idx_transport_service_supplier');

        $this->addSql('ALTER TABLE hotel DROP COLUMN supplier_id');
        $this->addSql('ALTER TABLE guide DROP COLUMN supplier_id');
        $this->addSql('ALTER TABLE transport_service DROP COLUMN supplier_id');

        // drop join table and new tables
        $this->addSql('ALTER TABLE supplier_region DROP CONSTRAINT fk_supplier_region_supplier');
        $this->addSql('ALTER TABLE supplier_region DROP CONSTRAINT fk_supplier_region_region');
        $this->addSql('DROP TABLE supplier_region');
        $this->addSql('DROP TABLE supplier');
        $this->addSql('DROP TABLE region');
    }
}

